
[config]
schemaVersion = "0.0.1"

[package]
namespace = "xiaoxiao921"
name = "OverlayDearImGui_Shared"
versionNumber = "2.0.0"
description = "Overlay Window for Dear ImGui"
websiteUrl = "https://github.com/xiaoxiao921/OverlayDearImGui"
containsNsfwContent = false

[package.dependencies]
bbepis-BepInExPack = "5.4.2109"

[build]
icon = "../icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./ReleaseOutput"
target = "./plugins/OverlayDearImGui.Shared"

[publish]
repository = "https://thunderstore.io"
communities = ["riskofrain2"]
categories = ["libraries"]